### ISSUE TITLE
Introduce quiet mode for install

### ISSUE THREAD

**Issue by saw303** [sdkman/sdkman-cli#101]
I am trying to use GVM with Travis-CI but failed because the `install` command requires user input.

``` yml
language: java

jdk:
  - openjdk7
  - oraclejdk7

before_install:
 - rm -Rf /home/travis/.gvm  # remove previous versions of GVM
 - curl -s get.gvmtool.net | bash
 - source "/home/travis/.gvm/bin/gvm-init.sh"
 - gvm install grails 2.2.0

script: grails test-app
```

This ends up waiting for a user input.

```
Do you want to use grails 2.2.0 now? (Y/n): 
```

It would be nice if there was a parameter to switch off user input (quiet mode)

```
gvm install -q grails 2.2.0
```
