### ISSUE TITLE
Bug: [/scripts-131430-121129324/step_script: /root/.sdkman/bin/sdkman-init.sh: line 75: syntax error: unexpected "("]

### ISSUE THREAD

**Issue by patpatpat123** [sdkman/sdkman-cli#1324]
**Bug report**

```
$ source "/root/.sdkman/bin/sdkman-init.sh"
/scripts-131430-121129324/step_script: /root/.sdkman/bin/sdkman-init.sh: line 75: syntax error: unexpected "("
```

**To reproduce**

Step 1: in Gitlab CI/CD, build a very simple job which only runs SDKMAN:
```
build-without-sock:
  image: docker:stable
  stage: build
  script:
    - apk add curl
    - apk add bash
    - apk add unzip
    - apk add zip
    - curl -s "https://get.sdkman.io" | bash
    - source "/root/.sdkman/bin/sdkman-init.sh"
    - sdk version
```

Reproducible 100%, the line ```source "/root/.sdkman/bin/sdkman-init.sh"``` would yield ```/scripts-131430-121129324/step_script: /root/.sdkman/bin/sdkman-init.sh: line 75: syntax error: unexpected "("```

**System info**

It is a base very famous docker:stable image
