### ISSUE TITLE
Question: [Installation with WSL 1]

### ISSUE THREAD

**Issue by stephanmg** [sdkman/sdkman-cli#770]
- [x] I have checked [the documentation](https://sdkman.io/usage)
- [x] I have done a quick search in [past issues](https://github.com/rclone/rclone/issues?q=) or [Stack Overflow](https://stackoverflow.com/questions/tagged/sdkman) for similar problems
- [x] I have brought up a conversation in the [Slack User Issues Channel](https://sdkman.slack.com/app_redirect?channel=user-issues)

**Question**

I was following the documentation to install on Windows. I'm using Windows 10 on Appveyor.
I installed WSL 1.

However, this fails:
 source "/c/Users/appveyor/.sdkman/bin/sdkman-init.sh"

With error:
'source' is not recognized as an internal or external command,

I'm not quiet sure why. Bash seems to be installed.

**System info**

Windows 10 x64 VM on Appveyor.

**Comment by marc0der** [comment]
Hi @stephanmg,

It is very difficult to tell what is going wrong with the little information you have given.

However, the fact that it is failing by not knowing what `source` is makes me think that you are trying to run it in a windows cmd shell, not a cygwin (or WSL) shell. It would be helpful if you could paste the exact procedure that you followed, plus any console output that you see when installing.

**Comment by stephanmg** [comment]
@marc0der you are right. I provided defintely too little detail.

Here is my installation routine with error logs:
https://ci.appveyor.com/project/stephanmg/branch-generator/builds/33843154

**Comment by marc0der** [comment]
It seems like your `install.sh` is not finding the files installed in the previous (installation) step. Have you tried running `install.sh` locally first in a bash terminal?

If it behaves the same locally it would be a problem with the script, else you might need to take it up with the AppVeyor community.

**Comment by stephanmg** [comment]
Right now I do not have a Windows installation at my hands. Thus I cannot test it. In the install script once checks for cygwin but not for WSL.

**Comment by marc0der** [comment]
@stephanmg would you mind sharing how you resolved this for the benefit of others who might face the same issue?

**Comment by stephanmg** [comment]
@marc0der sure. But I think I was rather not using WSL correctly, here is my CI script for Appveyor:

image: Visual Studio 2019

```
install:
  - wsl sudo apt-get update
  - wsl sudo apt-get install -y zip
  - curl -s "https://get.sdkman.io" | wsl bash
  - wsl source "/home/appveyor/.sdkman/bin/sdkman-init.sh"
  - wsl bash -c "echo source /home/appveyor/.bashrc >> /home/appveyor/.bash_profile"
  - wsl bash -c "echo source /home/appveyor/.bashrc >> /home/appveyor/.profile"
  - ps: wsl bash -c "source /home/appveyor/.sdkman/bin/sdkman-init.sh && sdk install kotlin &> /dev/null" 
  
environment:
  JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

```
